import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next.js demo</h1>

        <p className={styles.description}>
          A small demo discovering{" "}
          <code className={styles.code}>cool features</code>
        </p>

        <h2 className={styles.subtitle}>Rendering</h2>

        <div className={styles.grid}>
          <Link href="/ssg/post">
            <div className={styles.card}>
              <h2>SSG example &rarr;</h2>
              <p>Static-site generation</p>
            </div>
          </Link>
          <Link href="/csr/post">
            <div className={styles.card}>
              <h2>CSR example &rarr;</h2>
              <p>Client-side rendering</p>
            </div>
          </Link>
          <Link href="/ssr/post">
            <div className={styles.card}>
              <h2>SSR example &rarr;</h2>
              <p>Server-side rendering</p>
            </div>
          </Link>
          <Link href="/isr/post">
            <div className={styles.card}>
              <h2>ISR example &rarr;</h2>
              <p>Incremental Static Regeneration</p>
            </div>
          </Link>
          <Link href="/isr-csr/post">
            <div className={styles.card}>
              <h2>ISR+CSR example &rarr;</h2>
              <p>Incremental Static Regeneration + Client-side rendering</p>
            </div>
          </Link>
        </div>

        <h2 className={styles.subtitle}>Image Optimization</h2>

        <div className={styles.grid}>
          <Link href="/image">
            <div className={styles.card}>
              <h2>Image component &rarr;</h2>
              <p>Dynamically load images when entering viewport</p>
            </div>
          </Link>
        </div>

        <h2 className={styles.subtitle}>Dynamic Import</h2>

        <div className={styles.grid}>
          <Link href="/dynamic">
            <div className={styles.card}>
              <h2>Dynamic import &rarr;</h2>
              <p>Serve modules only when needed</p>
            </div>
          </Link>
        </div>
      </main>
    </div>
  );
}
